- hosts: all
  tasks:
    - name: stop container
      shell:  docker container stop democontainer                   #name of container 
    - name: remove container
      shell: docker container rm democontainer
    - name: remove docker image
      shell: docker image rm satishy1566/democontainer                            #name of images (docker images)
    - name: create new container
      shell: docker container run -itd --name democontainer -p 9000:80 satishy1566/satish     #(docker-job>> name of jenkins job)
